version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.avseedgeproject.integrations:TestEdgeRunTime
  packages:
  - name: EdgeAvseEdgeProject
    version: "1.0"
- serviceName: pub.date:getCurrentDateString
  packages:
  - name: WmPublic
    version: 11.0.0.0.396
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.396
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.0.0.0.396
- serviceName: TestOrigin:getAccountDetails
  packages:
  - name: EdgeRepo
    version: "1.0"
- serviceName: edge.avseedgeproject.integrations:TestEgdeServiceOnSaaS
  packages:
  - name: EdgeAvseEdgeProject
    version: "1.0"
  - name: EdgeRepo
    version: "1.0"
- serviceName: pub.io:streamToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.396
packages:
- name: EdgeAvseEdgeProject
  gitServerName: SelviGitHub
  gitUrl: https://github.com/AvudaiSelvi/EdgeAvseEdgeProject
  gitUsername: AvudaiSelvi
  gitToken: edge.scaffolding.EdgeAvseEdgeProject.SelviGitHub.gitToken
  gitBranch: master
- name: EdgeRepo
  gitServerName: SelviGitHub
  gitUrl: https://github.com/AvudaiSelvi
  gitUsername: AvudaiSelvi
  gitToken: edge.scaffolding.EdgeRepo.SelviGitHub.gitToken
  gitBranch: main
